FROM registry.access.redhat.com/ubi9/python3.9

#Needed to remove warning about frozen modules
ENV PYDEVD_DISABLE_FILE_VALIDATION=1

EXPOSE 5678 5000

ADD app.py /opt/app-root
ADD requirements.txt /opt/app-root

WORKDIR /opt/app-root

# Install dependencies
RUN pip install -r requirements.txt


CMD flask run --host 0.0.0.0
# To configure debugging using remote facility we could change the previous command to: 
# pip install debugpy -t /tmp && \
#    python /tmp/debugpy --listen 0.0.0.0:5678 --wait-for-client -m flask run --host=0.0.0.0
# However we are burying the debugpy module into the container.
# Instead, it is better to run the container:
# podman run -p 5000:5000 -p 5678:5678 quay.io/rhn-gls-rtaniguchi/python-app sh -c 'pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:5678 --wait-for-client -m flask run --host=0.0.0.0'
